### PR TITLE
[WIP] Rewrite of client to Polymer

### PR DESCRIPTION
**Pull request by TimvdLippe**
Polymer ftw. It's just awesome.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Port is almost finished. Below a list of TODO's:
- [x] On resize, send the updated event to server
- [x] On move, send the updated event to server
- [x] Look into Material design borders https://www.google.com/design/spec/components/data-tables.html#data-tables-structure
  - [x] Create horizontal borders
  - [x] Adjust colors of headers

**Comment by TimvdLippe** [comment]
PR ready for me.

**Comment by GijsWeterings** [comment]
All seems good. Let's merge the other pull request and merge this to master

**Comment by TimvdLippe** [comment]
Verified working. Merging!

**Pull request merged**
