### PR TITLE
Feature/edit modal

### LINKED ISSUE #5: Make it possible to edit events without drag/dropping
Edit date/time of event in a modal window. Should be mobile-friendly to use

### PR DESCRIPTION
**Pull request by TimvdLippe**
Requires https://github.com/Mentoraat/plannings-tool-server/pull/9

Closes #5 #6

### CODE REVIEW

**Comment by TimvdLippe** [comment]
@GijsWeterings can you LGTM?

**Comment by GijsWeterings** [comment]
Is it intended behaviour I cannot finish a lecture block? (don't get a popup at all)

I think we also need a duration/end time field, should be easy to implement. 

Did you do something with the positioning? In a few tries the modal wasn't centered properly. Might be a modal bug?

otherwise LGTM

**Comment by TimvdLippe** [comment]
> Is it intended behaviour I cannot finish a lecture block? (don't get a popup at all)

Yes, these events are not editable. `event.editable === false`

> I think we also need a duration/end time field, should be easy to implement.

Yes indeed, will add it in!

> Did you do something with the positioning? In a few tries the modal wasn't centered properly. Might be a modal bug?

No I didn't, might be a bug in `paper-dialog`

**Comment by GijsWeterings** [comment]
If locked events are not finishable by hand, do we finish them automatically past end date? Otherwise it'd probably het confusing in the "not done" stack

**Comment by GijsWeterings** [comment]
Lgtm!

**Pull request merged**
