### PR TITLE
Switch production generation to polymer build

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR makes use of the new polymer build.

Make sure to install the new dependencies with `npm install`.
Generate a build with `npm run build`.

You will need a special version of `polyserve` to serve the website.
1. `git clone https://github.com/TimvdLippe/polyserve`
2. `cd polyserve/`
3. Switch to branch `proxy`
4. `npm install`
5. `npm run build`
6. `rm -rf /usr/local/lib/node_modules/polyserve/`
7. `cp -a . /usr/local/lib/node_modules/polyserve/`

Then serve (after generating build) with

```
polyserve --root build/unbundled/ -P h2 --proxy-root v1 --proxy-target localhost --proxy-port 9000
```

### CODE REVIEW

**Comment by GijsWeterings** [comment]
Statically looks pretty good, still need to fix travis/jshint ;) Will test out tomorrow!

**Comment by TimvdLippe** [comment]
@GijsWeterings I fixed the build :tada: You can now run `npm install` and then `npm run serve` to serve the local dev environment. Similarly you can run `npm run build && npm run serve-build` to serve the production version.

**Review by GijsWeterings — CHANGES_REQUESTED** [review]
Only thing: /styles/ is only generated during build. Needs to also run for serve

**Comment by GijsWeterings** [comment]
after last fix, you can merge it!

**Comment by TimvdLippe** [comment]
@GijsWeterings when you `npm install` the styles are generated

**Pull request merged**
