### PR TITLE
Create a bar per course

### PR DESCRIPTION
**Pull request by TimvdLippe**
Requires https://github.com/Mentoraat/plannings-tool-server/pull/40

### CODE REVIEW

**Comment by GijsWeterings** [comment]
Few remarks here:
- On what period of time to the bars display their stats? They don't seem to change when I navigate to next week
- We now have all courses under eachother, requiring the user to scroll to see them. This never creates a full view of progression. Would it be an idea to view the current week's progress, together with a "more statistics" button to view the other bars?
- Microwave Sensors and Radars for Airport Applications is completely light grey for me. If a course is irrelevant/over, can we hide them?

**Comment by TimvdLippe** [comment]
- They are for the whole course, not per week. If you suddenly have a big deadline it is worth more than all separate assignments. (and it is easier to program ;) )
- Normally only 3 courses are shown, 6 is debugging. These should fit right?
- Yes that one does not have any assignments, so it has 0,0,0

**Comment by GijsWeterings** [comment]
So we're not doing week-based tracking as well? That was my understanding tbh. The system as it works now could work for a quarter, but what if I skip to next quarter as an eager student? _cough_

**Comment by TimvdLippe** [comment]
Currently nothing is working per week, only the default calendar view. I think if we change this to per week, we should update the assignments panel and all calculations. Preferably we do this in 1 go on the server instead.

**Comment by GijsWeterings** [comment]
agreed! LGTM

**Pull request merged**
